server:
  port: 9191

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: SampleRealm
  resource: sb-app
  public-client: true
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /me
  principal-attribute: preferred_username
logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: TRACE
